bcgov/visitz-api

- helm/templates/deployment.yaml
- src/main.ts
This PR will force the image to be pulled each time a container is created
> Add imagePullPolicy: Always

- .github/workflows/build-and-push-ghcr.yaml
> try to auto rollout pod

- src/common/constants/parameter-constants.ts
Change service account view mode to 'Catalog'
> change view mode to catalog

- src/common/guards/auth/auth.service.spec.ts
- src/common/guards/auth/auth.service.ts
Fix auth header name for idir to the one actually used
> fix auth header name

- src/common/guards/auth/auth.guard.ts
> fixing async bug

- src/configuration/configuration.ts
- src/controllers/service-requests/service-requests.controller.spec.ts
- src/controllers/service-requests/service-requests.controller.ts
Add Auth Guard to service requests endpoints.
> Service request Auth Guard

- helm/templates/deployment.yaml
- src/controllers/service-requests/service-requests.controller.spec.ts
> env variable config change

- .env.example
- .gitignore
- cypress.config.ts
- cypress/e2e/cases.spec.cy.ts
- cypress/support/e2e.ts
- cypress/tsconfig.json
- docs/decisions/0013-choose-an-e2e-api-testing-framework.md
- eslint.config.mjs
- package-lock.json
- package.json
- tsconfig.json
[Story link](https://bcsocialsector.service-now.com/now/nav/ui/classic/params/target/rm_story.do%3Fsys_id%3D8263e790fb0a56104e3aff907befdc22%26sysparm_view%3Dscrum%26sysparm_record_target%3Drm_story%26sysparm_record_row%3D33%26sysparm_record_rows%3D36%26sysparm_record_list%3Depic%253Db96a9b1d931dd210e09fb1584dba1091%255EORDERBYnumber)
This PR adds an ADR for the API testing framework decision, as well as an example for the chosen framework, Cypress.
> API Testing Framework

- .env.example
- .github/workflows/build-and-push-ghcr.yaml
- helm/templates/deployment.yaml
- helm/values.yaml
- src/configuration/configuration.ts
- Updated workspace parameters to be environment variable based
- Updated upstream url to use github actions secret instead of OpenShift secret
> Moving workspace parameters to environment variables

- src/entities/contacts.entity.ts
[Story link](https://bcsocialsector.service-now.com/rm_story.do?sys_id=6e374deffb165a104e3aff907befdc5e&sysparm_view=&sysparm_time=1734034537352)
Editing fields to add metadata and two missing fields, and removing extraneous ones.
> Editing Contact Details fields

- .github/workflows/build-and-push-ghcr.yaml
> Fix ubuntu version to include oc command

- src/configuration/configuration.ts
- src/entities/attachments.entity.ts
- src/entities/in-person-visits.entity.ts
Reverting metadata changes that were not added to the visits and attachments entities.
> Revert metadata changes

- src/configuration/configuration.ts
> Sales Rep field name change

- src/common/guards/auth/auth.service.ts
> Add accept encoding to show errors on auth

- src/common/guards/auth/auth.service.spec.ts
- src/common/guards/auth/auth.service.ts
> Check uniform response for idir field

- package-lock.json
- package.json
- src/app.module.ts
- src/common/guards/auth/auth.guard.ts
- src/common/guards/auth/auth.service.ts
- src/external-api/token-refresher/token-refresher.service.ts
[Story Link](https://bcsocialsector.service-now.com/rm_story.do?sys_id=fcc6496ffb165a104e3aff907befdcec&sysparm_view=scrum&sysparm_record_target=rm_story&sysparm_record_row=40&sysparm_record_rows=49&sysparm_record_list=epic%3Db96a9b1d931dd210e09fb1584dba1091%5EORDERBYnumber)
This PR adds a defined structure for audit logs, which omits sensitive info like bearer tokens. It also logs the authorization status of auth requests, which may differ from the status code presented to the user. Note that 401 errors cannot be logged, as they are caught before they reach the NestJS container.
> Security Audit Logs

- src/common/guards/auth/auth.guard.ts
Title. Adds log for this purpose.
> Check if jwt is provided in request

- src/common/constants/upstream-constants.ts
- src/common/guards/auth/auth.guard.ts
- src/common/guards/auth/auth.service.spec.ts
- src/common/guards/auth/auth.service.ts
- src/controllers/cases/cases.controller.spec.ts
- src/controllers/cases/cases.controller.ts
- src/controllers/cases/cases.service.spec.ts
- src/controllers/cases/cases.service.ts
- src/controllers/incidents/incidents.controller.spec.ts
- src/controllers/incidents/incidents.controller.ts
- src/controllers/incidents/incidents.service.spec.ts
- src/controllers/incidents/incidents.service.ts
- src/controllers/memos/memos.controller.spec.ts
- src/controllers/memos/memos.controller.ts
- src/controllers/memos/memos.service.spec.ts
- src/controllers/memos/memos.service.ts
- src/controllers/service-requests/service-requests.controller.spec.ts
- src/controllers/service-requests/service-requests.controller.ts
- src/controllers/service-requests/service-requests.service.spec.ts
- src/controllers/service-requests/service-requests.service.ts
- src/external-api/request-preparer/request-preparer.service.spec.ts
- src/external-api/request-preparer/request-preparer.service.ts
- src/helpers/attachments/attachments.service.spec.ts
- src/helpers/attachments/attachments.service.ts
- src/helpers/contacts/contacts.service.spec.ts
- src/helpers/contacts/contacts.service.ts
- src/helpers/in-person-visits/in-person-visits.service.spec.ts
- src/helpers/in-person-visits/in-person-visits.service.ts
- src/helpers/support-network/support-network.service.spec.ts
- src/helpers/support-network/support-network.service.ts
> Dev -> test

- .env.example
- .github/workflows/build-and-push-ghcr.yaml
- helm/templates/deployment.yaml
- helm/values.yaml
- src/configuration/configuration.ts
[Story Link](https://bcsocialsector.service-now.com/rm_story.do?sys_id=4d4accfcfbd752504e3aff907befdc90&sysparm_view=&sysparm_time=1737654749870)
Forces skipJWTCache and skipAuthGuard to false when in production environment.
> Feature: Implement global meta environment variable

- src/common/constants/parameter-constants.ts
Change view mode from Catalog -> Organization
> Parameter change

- .github/workflows/codeql.yaml
> Add codeql to main for gh to detect it

- .github/workflows/codeql.yaml
> Add CodeQL to dev

- .github/workflows/codeql.yaml
> CodeQL change -> dev

- docs/decisions/0014-choose-an-antivirus-solution.md
- docs/decisions/0014-choose-an-antivirus.md
> ADR: Antivirus scanning solution

- docs/decisions/0009-upstream-base-authorization.md
[STRY0036902 - Write ADR for new authorization architecture](https://bcsocialsector.service-now.com/rm_story.do?sys_id=c05f3e96333f1e1084a805570e5c7ba5&sysparm_view=&sysparm_time=1740160497263)
Adding an ADR for our base authz/n mechanism with upstream Siebel.
> Add initial draft of upstream base authorization

- clamav/Dockerfile
- clamav/clamdcheck.sh
- clamav/config/clamd.conf
- clamav/config/freshclam.conf
Title. Add additional config files docker is looking for.
> Add configuration files

- clamav/Dockerfile
- clamav/docker-compose.yml
> Docker file changes

- clamav/Dockerfile
- clamav/docker-entrypoint-unprivileged.sh
> Fixing entrypoint for ClamAV

- .github/workflows/clamav-build-and-push.yaml
> Changing ClamAV rerollout from deployment to statefulset

- docs/decisions/0008-api-specification.md
- docs/decisions/0010-version-handling.md
- docs/decisions/0011-upstream-caching.md
- docs/decisions/0012-siebel-viewmode.md
- docs/decisions/0015-filtering-downstream-data.md
- docs/decisions/0016-timestamp-filtering.md
[STRY0036908 - Write remaining ADRs for API middleware](https://bcsocialsector.service-now.com/rm_story.do?sys_id=cfd8deaa33bf5e1084a805570e5c7b34&sysparm_view=&sysparm_time=1741027980219)
> Add remaining ADRs

- src/common/guards/auth/auth.service.ts
Change view for employee to 'Catalog'
> Change employee view to catalog to prevent errors

- src/configuration/configuration.ts
- src/entities/attachments.entity.ts
[Story Link](https://bcsocialsector.service-now.com/rm_story.do?sys_id=a21f945cfb48a6944e3aff907befdcb7&sysparm_view=&sysparm_time=1741365099374)
Updating fields in Attachments to match the current state of the objects.
> Attachments updates

- docs/ONBOARDING.md
Added a blurb explaining a bit about environment variables and development dependencies.
> Update onboarding docs

- src/entities/incident.entity.ts
- src/entities/memo.entity.ts
[Ensure field consistency with upstream](https://bcsocialsector.service-now.com/rm_story.do?sys_id=f24d790cfb5022d04e3aff907befdcdb&sysparm_view=&sysparm_time=1741739624759)
> Fix Incident & Memo fields

- src/controllers/caseload/caseload.service.spec.ts
- src/controllers/caseload/caseload.service.ts
- src/entities/incident.entity.ts
[Perform Restricted Flag check in middleware instead of Siebel query](https://bcsocialsector.service-now.com/rm_story.do?sys_id=9ce828a83354ee1484a805570e5c7b63&sysparm_view=&sysparm_time=1741803428386)
> Restricted file filtering

- src/entities/incident.entity.ts
- src/entities/memo.entity.ts
- src/entities/sr.entity.ts
[Remove KKCFS flag from API structures](https://bcsocialsector.service-now.com/rm_story.do?sys_id=72e68cbefb90ee144e3aff907befdcdc&sysparm_view=&sysparm_time=1742404146873)
> Remove KKCFS flag from entities

- src/controllers/memos/memos.controller.spec.ts
- src/controllers/memos/memos.controller.ts
["Get record and validate" component - Memos](https://bcsocialsector.service-now.com/nav_to.do?uri=rm_story.do?sys_id=0867f5b893bd1210e09fb1584dba1036%26sysparm_view=scrum)
> Enable memo auth

- package-lock.json
> Update package vulnerabilities

- .github/workflows/build-and-push-ghcr.yaml
- .github/workflows/clamav-build-and-push.yaml
- .github/workflows/unit-test.yaml
> Add explicit GH actions permissions

- src/common/guards/auth/auth.service.ts
- src/controllers/caseload/caseload.service.spec.ts
- src/controllers/caseload/caseload.service.ts
Remove the multivalue query from SRs and Memos as these can only have one assignee.
> Fix: Auth guard multivalue

- .github/workflows/build-and-push-ghcr.yaml
- .github/workflows/clamav-build-and-push.yaml
- .github/workflows/unit-test.yaml
[Story Link](https://bcsocialsector.service-now.com/rm_story.do?sys_id=dd829731fb4526104e3aff907befdc51&sysparm_view=&sysparm_time=1745507470055)
This will have to be merged through to main in order to clear the security alerts.
> Update workflow actions to pinned tags

- .github/workflows/build-and-push-ghcr.yaml
- .github/workflows/clamav-build-and-push.yaml
> Disable docker summary

- clamav/README.md
- docs/RELEASES.md
Added information on clamav deployment to releases.md
> Added a section on ClamAV to releases.md

- helm/Chart.yaml
- package-lock.json
Updating packages and helm chart for release.
> Release: v1.0.0

- helm/Chart.yaml
[Story Link](https://bcsocialsector.service-now.com/rm_story.do?sys_id=359c82c22bd52e50f81ff644ce91bf13&sysparm_view=&sysparm_time=1746464742679)
> Release: Visitz API v1.0.1 (dev)

- src/common/guards/auth/auth.service.ts
- src/controllers/caseload/caseload.controller.spec.ts
- src/controllers/caseload/caseload.controller.ts
- src/controllers/caseload/caseload.module.ts
- src/controllers/external-auth/external-auth.module.ts
- src/external-api/token-refresher/token-refresher.service.ts
- src/helpers/utilities/utilities.service.ts
[Story Link](https://bcsocialsector.service-now.com/rm_story.do?sys_id=249fb935fb71a2104e3aff907befdcdf&sysparm_view=&sysparm_time=1748620690764)
Add additional logs to auth related functions.
> Feat: Additional Auth Logs

- .env.example
- helm/visitz-config-values.yaml
- src/common/constants/parameter-constants.ts
- src/common/guards/auth/auth.service.spec.ts
- src/common/guards/auth/auth.service.ts
- src/configuration/configuration.ts
- src/entities/employee.entity.ts
- src/entities/position.entity.ts
[Story Link](https://bcsocialsector.service-now.com/rm_story.do?sys_id=36e138b5fb0a2a504e3aff907befdcda&sysparm_view=&sysparm_time=1750951830866)
This PR adds organizational filtering to API access.
> Feat: Implement organizational barrier to API access

- src/common/constants/parameter-constants.ts
- src/controllers/caseload/caseload.service.spec.ts
- src/controllers/caseload/caseload.service.ts
- src/entities/case.entity.ts
This PR adds the Position entity to caseload, allowing to see all the assigned IDIRs to a particular case.
> Feat: Add case position to caseload

- .env.example
- helm/visitz-config-values.yaml
- src/configuration/configuration.ts
- src/controllers/workflows/workflows.service.ts
Add hotfix for differing workflow base url.
> Fix: URL base for workflows

- src/common/guards/auth/auth.service.spec.ts
- src/common/guards/auth/auth.service.ts
- src/external-api/request-preparer/request-preparer.service.spec.ts
- src/external-api/request-preparer/request-preparer.service.ts
[Story Link](https://bcsocialsector.service-now.com/rm_story.do?sys_id=41f156282bab2690f81ff644ce91bfdb&sysparm_view=&sysparm_time=1756493037858)
> Feature: status code update

- src/controllers/caseload/caseload.service.spec.ts
- src/helpers/utilities/utilities.service.ts
> Release: Visitz v2.2.0 (development)
